# Generated by Django 3.2.5 on 2021-08-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True)),
                ('pokedex_id', models.IntegerField(blank=True)),
                ('base_experience', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('weight', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='verybasic',
        ),
    ]
