# Generated by Django 3.2.5 on 2021-08-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0002_auto_20210802_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypokemon',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='mypokemon',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
