# Generated by Django 3.2.5 on 2021-08-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0003_auto_20210802_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
