# Generated by Django 3.2.5 on 2021-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pokedex', '0004_mypokemon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypokemon',
            name='sprite',
            field=models.CharField(default='', max_length=100),
        ),
    ]
