# Generated by Django 3.2.5 on 2021-07-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='verybasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hello', models.TextField(blank=True)),
                ('pokemon', models.BooleanField(default=True)),
                ('price', models.IntegerField(default=100)),
                ('description', models.TextField(default='hello my pokemon')),
            ],
        ),
    ]
